# Generated by Django 3.0.3 on 2020-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
